export const mockCompanies = [
  {
    id: 1,
    name: "Notion",
    website: "https://www.notion.so",
    sector: "Productivity",
    stage: "Series C+",
    description: "Workspace platform that combines docs, wikis, and project management for modern teams.",
    status: "Active",
  },
  {
    id: 2,
    name: "Linear",
    website: "https://linear.app",
    sector: "Developer Tools",
    stage: "Series C",
    description: "Issue tracking and project management designed for high-performing product and engineering teams.",
    status: "Active",
  },
  {
    id: 3,
    name: "Vercel",
    website: "https://vercel.com",
    sector: "Developer Infrastructure",
    stage: "Series D+",
    description: "Frontend cloud platform for developing, previewing, and shipping high-performance web applications.",
    status: "Active",
  },
  {
    id: 4,
    name: "Datadog",
    website: "https://www.datadoghq.com",
    sector: "Observability",
    stage: "Public",
    description: "Monitoring and security platform for cloud applications, aggregating metrics, traces, and logs.",
    status: "Active",
  },
  {
    id: 5,
    name: "Stripe",
    website: "https://stripe.com",
    sector: "Fintech / Payments",
    stage: "Late Stage",
    description: "Payments and financial infrastructure platform for internet businesses of all sizes.",
    status: "Active",
  },
  {
    id: 6,
    name: "OpenAI",
    website: "https://openai.com",
    sector: "AI / Foundation Models",
    stage: "Late Stage",
    description: "Research and deployment company building general-purpose AI models and developer platforms.",
    status: "Active",
  },
  {
    id: 7,
    name: "Anthropic",
    website: "https://www.anthropic.com",
    sector: "AI Safety & Research",
    stage: "Late Stage",
    description: "AI safety and research company focused on building reliable, steerable, and interpretable AI systems.",
    status: "Active",
  },
  {
    id: 8,
    name: "Snowflake",
    website: "https://www.snowflake.com",
    sector: "Data Warehouse",
    stage: "Public",
    description: "Cloud-native data platform for analytics, warehousing, and secure data sharing at scale.",
    status: "Active",
  },
  {
    id: 9,
    name: "Cloudflare",
    website: "https://www.cloudflare.com",
    sector: "Security / Edge",
    stage: "Public",
    description: "Global cloud network delivering security, performance, and edge compute for internet applications.",
    status: "Active",
  },
  {
    id: 10,
    name: "Figma",
    website: "https://www.figma.com",
    sector: "Design Collaboration",
    stage: "Late Stage",
    description: "Collaborative interface design and prototyping platform used by product and design teams.",
    status: "Active",
  },
  {
    id: 11,
    name: "Supabase",
    website: "https://supabase.com",
    sector: "Developer Tools",
    stage: "Series C",
    description: "Open source Firebase alternative providing Postgres databases, authentication, instant APIs, and storage.",
    status: "Active",
  },
  {
    id: 12,
    name: "Hugging Face",
    website: "https://huggingface.co",
    sector: "AI / ML Hub",
    stage: "Series D",
    description: "The AI community building the future. A platform for machine learning models, datasets, and applications.",
    status: "Active",
  },
  {
    id: 13,
    name: "Deel",
    website: "https://www.deel.com",
    sector: "HR Tech",
    stage: "Late Stage",
    description: "Global compliance and payroll solution that helps companies hire anyone, anywhere.",
    status: "Active",
  },
  {
    id: 14,
    name: "Perplexity",
    website: "https://www.perplexity.ai",
    sector: "AI Search",
    stage: "Series B",
    description: "AI-powered conversational search engine that provides direct answers with cited sources.",
    status: "Active",
  },
  {
    id: 15,
    name: "Retool",
    website: "https://retool.com",
    sector: "Internal Tools",
    stage: "Series C",
    description: "Fast way to build internal tools. Drag-and-drop building blocks to create custom apps and dashboards.",
    status: "Active",
  },
  {
    id: 16,
    name: "Raycast",
    website: "https://www.raycast.com",
    sector: "Productivity",
    stage: "Series B",
    description: "Extendable launcher for macOS that lets you complete tasks, calculate, share common links, and more.",
    status: "Active",
  },
  {
    id: 17,
    name: "PostHog",
    website: "https://posthog.com",
    sector: "Analytics",
    stage: "Series B",
    description: "Open-source product analytics platform built for engineers to track events, record sessions, and run experiments.",
    status: "Active",
  },
  {
    id: 18,
    name: "Vanta",
    website: "https://www.vanta.com",
    sector: "Security / Compliance",
    stage: "Series C",
    description: "Automated security monitoring platform that helps companies achieve SOC 2, HIPAA, and ISO 27001 compliance.",
    status: "Active",
  },
  {
    id: 19,
    name: "Scale AI",
    website: "https://scale.com",
    sector: "Data Infrastructure",
    stage: "Late Stage",
    description: "Data platform for AI, providing high-quality training data for machine learning teams.",
    status: "Active",
  },
  {
    id: 20,
    name: "Pinecone",
    website: "https://www.pinecone.io",
    sector: "Database",
    stage: "Series B",
    description: "Managed vector database designed to build and scale generative AI applications quickly.",
    status: "Active",
  },
  {
    id: 21,
    name: "LangChain",
    website: "https://www.langchain.com",
    sector: "AI Tools",
    stage: "Series A",
    description: "Framework for developing applications powered by language models with composability.",
    status: "Active",
  },
  {
    id: 22,
    name: "Resend",
    website: "https://resend.com",
    sector: "Developer Tools",
    stage: "Series A",
    description: "Email API for developers. Build, test, and deliver transactional emails at scale.",
    status: "Active",
  },
  {
    id: 23,
    name: "Rippling",
    website: "https://www.rippling.com",
    sector: "HR / IT",
    stage: "Late Stage",
    description: "Workforce management platform unifying HR, IT, and Finance into a single system.",
    status: "Active",
  },
  {
    id: 24,
    name: "ElevenLabs",
    website: "https://elevenlabs.io",
    sector: "AI Audio",
    stage: "Series B",
    description: "AI voice generator offering hyper-realistic text-to-speech and voice cloning software.",
    status: "Active",
  },
  {
    id: 25,
    name: "Glean",
    website: "https://www.glean.com",
    sector: "Enterprise Search",
    stage: "Series D",
    description: "AI-powered work assistant and enterprise search platform that connects across all company apps.",
    status: "Active",
  }
];